apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: security-pipeline
spec:
  params:
    - default: deploy
      name: action
      type: string
    - default: pss
      name: department
      type: string
    - default: dc
      name: location
      type: string
  tasks:
    - name: git-clone
      params:
        - name: URL
          value: https://github.com/wael2000/dora
        - name: refspec
          value: ''
        - name: submodules
          value: 'true'
        - name: depth
          value: '1'
        - name: sslVerify
          value: 'true'
        - name: crtFileName
          value: ca-bundle.crt
        - name: subdirectory
          value: ''
        - name: sparseCheckoutDirectories
          value: ''
        - name: deleteExisting
          value: 'true'
        - name: httpProxy
          value: ''
        - name: httpsProxy
          value: ''
        - name: noProxy
          value: ''
        - name: verbose
          value: 'true'
        - name: gitInitImage
          value: >-
            registry.redhat.io/openshift-pipelines/pipelines-git-init-rhel8@sha256:868966ef9d4b54952d8a74eb83bba40eb1f52c0148994fa704efd0e3797c61c5
        - name: userHome
          value: /home/git
        - name: REVISION
          value: ocp4.17
      taskRef:
        params:
          - name: kind
            value: task
          - name: name
            value: git-clone
          - name: namespace
            value: openshift-pipelines
        resolver: cluster
      workspaces:
        - name: output
          workspace: source
    - name: apply-rbac
      params:
        - name: SCRIPT
          value: oc apply -f  gitops/rbac-applicationset.yaml
        - name: VERSION
          value: latest
      runAfter:
        - git-clone
      taskRef:
        params:
          - name: kind
            value: task
          - name: name
            value: openshift-client
          - name: namespace
            value: openshift-pipelines
        resolver: cluster
      when:
        - input: $(params.action)
          operator: in
          values:
            - deploy
      workspaces:
        - name: manifest_dir
          workspace: source
    - name: remove-rbac
      params:
        - name: SCRIPT
          value: oc delete -f  gitops/rbac-applicationset.yaml
        - name: VERSION
          value: latest
      runAfter:
        - git-clone
      taskRef:
        params:
          - name: kind
            value: task
          - name: name
            value: openshift-client
          - name: namespace
            value: openshift-pipelines
        resolver: cluster
      when:
        - input: $(params.action)
          operator: in
          values:
            - remove
      workspaces:
        - name: manifest_dir
          workspace: source
  workspaces:
    - name: source
      optional: false
  finally: []
