apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: galera-01
spec:
  dataVolumeTemplates:
    - metadata:
        name: galera-01-peach-haddock-85-volume
      spec:
        sourceRef:
          kind: DataSource
          name: rhel8
          namespace: openshift-virtualization-os-images
        storage:
          accessModes:
            - ReadWriteMany
          resources:
            requests:
              storage: 30Gi
          storageClassName: ocs-external-storagecluster-ceph-rbd
          volumeMode: Block
  instancetype:
    name: u1.medium
  preference:
    name: rhel.8
  running: true
  template:
    metadata:
      labels:
        network.kubevirt.io/headlessService: headless
        vm.kubevirt.io/name: galera-01
        galera/cluster: galera
    spec:
      domain:
        devices: {}
      subdomain: headless
      volumes:
        - dataVolume:
            name: galera-01-peach-haddock-85-volume
          name: rootdisk
        - cloudInitNoCloud:
            userData: |              
              #cloud-config
              user: cloud-user
              password: cloud8@123
              chpasswd: { expire: False }
              rh_subscription:
                activation-key: demo
                org: 10899047
                auto-attach: true
              runcmd:
                - sudo subscription-manager repos --list-enabled
                - sudo dnf module install -y mariadb/galera
                - |
                    cat <<EOF | sudo tee /etc/my.cnf
                    #
                    # This group is read both both by the client and the server
                    # use it for options that affect everything
                    #
                    [client-server]

                    [galera]
                    wsrep_on=ON
                    wsrep_cluster_name=rws
                    binlog_format=ROW
                    bind-address=0.0.0.0

                    default-storage-engine=InnoDB
                    innodb_autoinc_lock_mode=2
                    innodb_doublewrite=1
                    query_cache_size=0
                    wsrep_provider=/usr/lib64/galera-4/libgalera_smm.so

                    wsrep_cluster_address=gcomm://

                    wsrep_sst_method=rsync
                    wsrep_dirty_reads=ON
                    wsrep-sync-wait=0

                    wsrep_node_address=galera-01

                    #
                    # include all files from the config directory
                    #
                    !includedir /etc/my.cnf.d
                    EOF
                - sudo systemctl start mariadb
                - sudo systemctl status mariadb
                - mysql -u root -e "SHOW STATUS LIKE 'wsrep_cluster_size';"
                - mysql -u root -e "create database sampledb;"
                - mysql -u root -e "create user 'userOSR' identified by 'WmyArnyFmiyKrt7n';"
                - mysql -u root -e "grant all privileges on sampledb.* to 'userOSR'@'%' identified by 'WmyArnyFmiyKrt7n';"
                - mysql -u root -e "flush privileges;"
              final_message: wael-Cloud-init has completed successfully!
          name: cloudinitdisk
---
apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: galera-02
spec:
  dataVolumeTemplates:
    - metadata:
        name: galera-02-peach-haddock-85-volume
      spec:
        sourceRef:
          kind: DataSource
          name: rhel8
          namespace: openshift-virtualization-os-images
        storage:
          accessModes:
            - ReadWriteMany
          resources:
            requests:
              storage: 30Gi
          storageClassName: ocs-external-storagecluster-ceph-rbd
          volumeMode: Block
  instancetype:
    name: u1.medium
  preference:
    name: rhel.8
  running: true
  template:
    metadata:
      labels:
        network.kubevirt.io/headlessService: headless
        vm.kubevirt.io/name: galera-02
        galera/cluster: galera
    spec:
      domain:
        devices: {}
      subdomain: headless
      volumes:
        - dataVolume:
            name: galera-02-peach-haddock-85-volume
          name: rootdisk
        - cloudInitNoCloud:
            userData: |              
              #cloud-config
              user: cloud-user
              password: cloud8@123
              chpasswd: { expire: False }
              rh_subscription:
                activation-key: demo
                org: 10899047
                auto-attach: true
              runcmd:
                - sudo subscription-manager repos --list-enabled
                - sudo dnf module install -y mariadb/galera
                - |
                    cat <<EOF | sudo tee /etc/my.cnf
                    #
                    # This group is read both both by the client and the server
                    # use it for options that affect everything
                    #
                    [client-server]

                    [galera]
                    wsrep_on=ON
                    wsrep_cluster_name=rws
                    binlog_format=ROW
                    bind-address=0.0.0.0

                    default-storage-engine=InnoDB
                    innodb_autoinc_lock_mode=2
                    innodb_doublewrite=1
                    query_cache_size=0
                    wsrep_provider=/usr/lib64/galera-4/libgalera_smm.so

                    wsrep_cluster_address=gcomm://galera-01,galera-02

                    wsrep_provider_options="ist.recv_bind=10.0.2.2" 

                    wsrep_sst_method=rsync
                    wsrep_dirty_reads=ON
                    wsrep-sync-wait=0

                    wsrep_node_address=galera-02

                    #
                    # include all files from the config directory
                    #
                    !includedir /etc/my.cnf.d
                    EOF
                - sudo systemctl start mariadb
                - sudo systemctl status mariadb
                - mysql -u root -e "SHOW STATUS LIKE 'wsrep_cluster_size';"
              final_message: wael-Cloud-init has completed successfully!
          name: cloudinitdisk
---
apiVersion: v1
kind: Service
metadata:
  name: galera-01
spec:
  selector:
    vm.kubevirt.io/name: galera-01
  ports:
    - protocol: TCP
      name: tcp-3306
      port: 3306
      targetPort: 3306
    - protocol: TCP
      name: tcp-4567
      port: 4567
      targetPort: 4567
    - protocol: TCP
      name: tcp-4568
      port: 4568
      targetPort: 4568
    - protocol: TCP
      name: tcp-4444
      port: 4444
      targetPort: 4444
    - protocol: UDP
      name: udp-4567
      port: 4567
      targetPort: 4567
---
apiVersion: v1
kind: Service
metadata:
  name: galera-02
spec:
  selector:
    vm.kubevirt.io/name: galera-02
  ports:
    - protocol: TCP
      name: tcp-3306
      port: 3306
      targetPort: 3306
    - protocol: TCP
      name: tcp-4567
      port: 4567
      targetPort: 4567
    - protocol: TCP
      name: tcp-4568
      port: 4568
      targetPort: 4568
    - protocol: TCP
      name: tcp-4444
      port: 4444
      targetPort: 4444
    - protocol: UDP
      name: udp-4567
      port: 4567
      targetPort: 4567
---
apiVersion: v1
kind: Service
metadata:
  name: galera
spec:
  selector:
    galera/cluster: galera
  ports:
    - protocol: TCP
      name: tcp-3306
      port: 3306
      targetPort: 3306
    - protocol: TCP
      name: tcp-4567
      port: 4567
      targetPort: 4567
    - protocol: TCP
      name: tcp-4568
      port: 4568
      targetPort: 4568
    - protocol: TCP
      name: tcp-4444
      port: 4444
      targetPort: 4444
    - protocol: UDP
      name: udp-4567
      port: 4567
      targetPort: 4567
#apiVersion: export.kubevirt.io/v1beta1
#kind: VirtualMachineExport
#metadata:
#  name: galera-01-export
#spec:
#  source:
#    apiGroup: "kubevirt.io" 
#    kind: VirtualMachine 
#    name: galera-01
#  ttlDuration: 1h
