apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: rhel-8
  namespace: vm-gitops
spec:
  dataVolumeTemplates:
    - metadata:
        name: rhel-8-peach-haddock-85-volume
      spec:
        sourceRef:
          kind: DataSource
          name: rhel8
          namespace: openshift-virtualization-os-images
        storage:
          accessModes:
            - ReadWriteMany
          resources:
            requests:
              storage: 30Gi
          storageClassName: ocs-storagecluster-ceph-rbd
          volumeMode: Block
  instancetype:
    name: u1.medium
  preference:
    name: rhel.8
  running: true
  template:
    metadata:
      labels:
        network.kubevirt.io/headlessService: headless
    spec:
      domain:
        devices: {}
      subdomain: headless
      volumes:
        - dataVolume:
            name: rhel-8-peach-haddock-85-volume
          name: rootdisk
        - cloudInitNoCloud:
            userData: |
              #cloud-config
              chpasswd:
                expire: false
              password: cloud8@123
              user: cloud-user
          name: cloudinitdisk
