apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: showcase 
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/max-scale: '5'     # Maximum number of pods
        autoscaling.knative.dev/min-scale: '0'     # Minimum number of pods
        autoscaling.knative.dev/target: '10'       # Concurrency Target (triggers scaling)
        autoscaling.knative.dev/target-utilization-percentage: '80'  # Scale up when 70% of target is reached
        autoscaling.knative.dev/window: 30s
    spec:
      containerConcurrency: 5    # Concurrency Limit (max requests per pod), requests above this limit are queued 
      containers:
        - image: quay.io/openshift-knative/showcase 
          env:
            - name: GREET 
              value: Hallo