apiVersion: cluster.open-cluster-management.io/v1beta1
kind: Placement
metadata:
  name: bm-placement
  namespace: openshift-gitops
spec:
  clusterSets:
    - default
  predicates:
    - requiredClusterSelector:
        labelSelector:
          matchLabels:
            provider: bm