# Dev Env
# -- [vadmin,vdev]/admin --
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: dev-admin-rb
  namespace: dev
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: admin
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: vdev
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: vadmin  
---
# -- vops/view --
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: dev-view-rb
  namespace: dev
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: view
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: vops
---
# SIT Env
# -- [vadmin,vops]/admin --
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: sit-admin-rb
  namespace: sit
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: admin
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: vops
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: vadmin  
---
# PROD Env
# -- [vadmin]/admin --
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: prod-admin-rb
  namespace: prod
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: admin
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: vadmin  
---
# -- [vopsn]/view --
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: prod-view-rb
  namespace: prod
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: view
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: vops  
---
# cluster wide
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: admin-view-crb
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: view
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: gadmin
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: vadmin